name: Deploy to GitHub Pages (Self-Hosted)

on:
  push:
    branches:
      - master 

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    name: Build & Deploy Static Site
    runs-on: ubuntu-latest 
    needs: jekyll-build
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v4
